[target.x86_64-linux-android]
linker = "/Users/ianrumac/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android26-clang"

[target.i686-linux-android]
linker = "/Users/ianrumac/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android26-clang"

[target.armv7-linux-androideabi]
linker = "/Users/ianrumac/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi26-clang"

[target.aarch64-linux-android]
linker = "/Users/ianrumac/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android26-clang"

