name: Trigger Superscript-iOS Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger_ios_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Superscript-iOS Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: superwall/Superscript-iOS
          event-type: update-build
